// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjysRAXUvqDiLzzkfX8O1aQE_4TzrmsD0',
    appId: '1:16404071961:web:98cbba4e42b514ef570c88',
    messagingSenderId: '16404071961',
    projectId: 'dwaya-17eff',
    authDomain: 'dwaya-17eff.firebaseapp.com',
    storageBucket: 'dwaya-17eff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9VzHq-YN8B65GZCOcof_-1013V6Hn99Q',
    appId: '1:16404071961:android:45c298e4796dcbd0570c88',
    messagingSenderId: '16404071961',
    projectId: 'dwaya-17eff',
    storageBucket: 'dwaya-17eff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDySsYPCj3ROhhhAWUCiF8c7MhLkfr3CRw',
    appId: '1:16404071961:ios:48417b18a8b4c6ef570c88',
    messagingSenderId: '16404071961',
    projectId: 'dwaya-17eff',
    storageBucket: 'dwaya-17eff.firebasestorage.app',
    iosBundleId: 'com.example.dwaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDySsYPCj3ROhhhAWUCiF8c7MhLkfr3CRw',
    appId: '1:16404071961:ios:48417b18a8b4c6ef570c88',
    messagingSenderId: '16404071961',
    projectId: 'dwaya-17eff',
    storageBucket: 'dwaya-17eff.firebasestorage.app',
    iosBundleId: 'com.example.dwaya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjysRAXUvqDiLzzkfX8O1aQE_4TzrmsD0',
    appId: '1:16404071961:web:afdf364d1a70b618570c88',
    messagingSenderId: '16404071961',
    projectId: 'dwaya-17eff',
    authDomain: 'dwaya-17eff.firebaseapp.com',
    storageBucket: 'dwaya-17eff.firebasestorage.app',
  );
}
